- id: python-unittest
  name: python-unittest
  description: Runs unittest discover to run Python based unit tests
  entry: python3 -m unittest discover -qb
  pass_filenames: false
  types: [python] 
  language: system
- id: python-unittest-win
  name: python-unittest
  description: Runs unittest discover to run Python based unit tests
  entry: python -m unittest discover -qb
  pass_filenames: false
  types: [python] 
  language: system
